### ISSUE TITLE
"Archive "sbc:stable" not found"

### ISSUE THREAD

**Issue by abma** [Spring-SpringBoard/SpringBoard-Core#108]
i've tried to run SpringBoard BA which seems to depend on sbc:stable.

there is no release of sbc:stable?!

-> please create a stable release of sbc :)

https://springrts.com/wiki/Rapid#Creating_a_release

**Comment by gajop** [comment]
There will be a stable release one day, until then... this workaround!

**Comment by abma** [comment]
the depends in other board-repos are disadvantageous, too:

https://github.com/Spring-SpringBoard/SpringBoard-ZK/blob/master/modinfo.lua (stable, too)
https://github.com/Spring-SpringBoard/SpringBoard-S44/blob/master/modinfo.lua (depends on the git name)
https://github.com/Spring-SpringBoard/SpringBoard-XTA/blob/master/modinfo.lua (depends on git, too)

:)

**Comment by gajop** [comment]
I'm aware of it, but it doesn't really matter, no users! I'll get it sorted when I think a stable version is close (SB really needs a new one).

**Comment by abma** [comment]
i could be the first tester at least ;-)

**Comment by gajop** [comment]
Although I'm already having Forb test some scenario editing stuff, I'll remember to take you up on that offer when it's more complete

**Comment by abma** [comment]
why did i add it to rapid when its not useable?

**Comment by gajop** [comment]
So I can make it usable and embed it in Chobby, and distribute to early testers.
Is there a specific thing you'd like to test? I can't make *everything* ready at this moment, because there's just too many things I've added/am adding. If you can name one thing, e.g. terrain editing or scenario editing for a specific game I could have it sorted out soon-ish.

**Comment by abma** [comment]
> Is there a specific thing you'd like to test?

dependencies in rapid / archives / downloader.

**Comment by gajop** [comment]
Oh and another thing about these rapid depends. I'm not sure if I'll end up using them in `modinfo.lua` as I need to change them all the time, and essentially never use them locally because I work on a development version. I think I might just make Chobby use dynamic mutators if that works (although that would make life difficult for other lobbies...).

This still makes it useful that these repositories are on rapid (as I can dynamically depend on `rapid://sbc:test` / `rapid://sbc:stable` / "SpringBoard $VERSION"), but the whole "rapid://" tag dependency in `modinfo.lua` `depends` table may not be useful unless it becomes a bit smarter/easier to configure.

**Comment by gajop** [comment]
oh and lol at the timing.

**Comment by gajop** [comment]
OK in that case, I've fixed ZK's dependency. The other two (S44/XTA) aren't on rapid yet, and I want to focus on getting BA/EVO/ZK ready first as I'm most familiar with them.

**Comment by abma** [comment]
> The other two (S44/XTA) aren't on rapid yet
i guess i don't understand:

http://s44.repo.springrts.com/
http://xta.repo.springrts.com/

s44 + xta are on rapid!

**Comment by abma** [comment]
i still don't get why you prefer the complicate "solution" and changed the dependency on all repos to sbc:test when you could just create sbc:stable

**Comment by gajop** [comment]
I'm talking about SB versions of those two. I haven't asked you to add them to rapid (yet) - didn't want to give you too many tasks (there will probably be more stuff later, like MCL & LD games).

Stable isn't made because it isn't stable yet. After https://github.com/Spring-SpringBoard/SpringBoard-Core/milestone/4 is out I'll make everything a stable.

PS: Using stable dependencies makes it difficult to test development versions. Thoughts on how to solve that?

**Comment by abma** [comment]
> PS: Using stable dependencies makes it difficult to test development versions. Thoughts on how to solve that?

keep the dependency to test versions and when making a release change to stable.
